version: 2

restore-cache: &restore-cache
  restore_cache:
    keys:
      - v1-{{ checksum "yarn.lock" }}

save-cache: &save-cache
  save_cache:
    key: v1-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache

jobs:
  test:
    docker:
      - image: circleci/node:8.10.0
      - image: confluentinc/cp-zookeeper:5.0.1
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
      - image: confluentinc/cp-kafka:5.0.1
        environment:
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      - image: confluentinc/cp-schema-registry:5.0.1
        environment:
          SCHEMA_REGISTRY_HOST_NAME: localhost
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'localhost:2181'
    steps:
      - checkout
      - *restore-cache
      - run: yarn config set yarn-offline-mirror ~/.cache/yarn
      - run: yarn
      - *save-cache
      - run: .circleci/wait-for-server.sh
      - run: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test
